# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Simple-Headers
version:      1.02
version_from: lib/Email/Simple/Headers.pm
installdirs:  site
requires:
    Email::Simple:                 
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
